stages:
  - build-and-test
  - dockerize-and-push
  - deploy
  
build-and-test:
  stage: build-and-test
  image: openjdk:13-jdk-alpine
  before_script:
    - apk add --no-cache bash
    - chmod +x ./scripts/check-envvar.sh
    - which bash
    - ./scripts/check-envvar.sh GCP_PROJECTID
    - ./scripts/check-envvar.sh GCP_INSTANCE
    - ./scripts/check-envvar.sh GCP_GITLAB_TOKENFILE
    - ./scripts/check-envvar.sh GCP_CLOUDSQL_TOKENFILE
    - ./scripts/check-envvar.sh GCP_CLOUDSQL_INSTANCE
    - ./scripts/check-envvar.sh GCP_CLOUDSQL_PASSWORD
    - javac --version
  script:
    - chmod +x ./gradlew
    - ./gradlew build jacocoTestReport
  artifacts:
    when: always
    paths:
      - build/reports/
      - build/libs/
  only:
    - master
  tags:
    - dind
    - docker

dockerize-and-push:
  stage: dockerize-and-push
  image: docker:19.03.5
  services:
    - docker:19.03.5-dind
  script:
    - export JAR_FILE="./build/libs/`ls ./build/libs`"
    - printf "jar path is \"$JAR_FILE\"\n"
    - docker login -u _json_key --password-stdin https://gcr.io < "$GCP_GITLAB_TOKENFILE"
    - cat $GCP_CLOUDSQL_TOKENFILE > ./token.json
    - docker build --build-arg JAR_FILE=$JAR_FILE --build-arg TOKEN_FILE=./token.json --tag gcr.io/$GCP_PROJECTID/$CI_PROJECT_NAME:$CI_COMMIT_SHA .
    - docker push gcr.io/$GCP_PROJECTID/$CI_PROJECT_NAME:$CI_COMMIT_SHA
  dependencies:
    - build-and-test
  only:
    - master
  tags:
    - dind
    - docker

deploy:
  stage: deploy
  image: python:2.7
  before_script:
    - echo "deb http://packages.cloud.google.com/apt cloud-sdk-jessie main" | tee /etc/apt/sources.list.d/google-cloud-sdk.list
    - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
    - apt-get update
    - apt-get -qq -y install google-cloud-sdk
  script:
    - gcloud auth activate-service-account --key-file "$GCP_GITLAB_TOKENFILE"
    - gcloud compute instances update-container $GCP_INSTANCE --project $GCP_PROJECTID --zone europe-west3-c --container-env INSTANCE=$GCP_CLOUDSQL_INSTANCE,SPRING_DATASOURCE_PASSWORD=$GCP_CLOUDSQL_PASSWORD --container-image gcr.io/$GCP_PROJECTID/$CI_PROJECT_NAME:$CI_COMMIT_SHA
  dependencies:
    - dockerize-and-push
  only:
    - master
  tags:
    - dind
    - docker


