server:
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: laden
---
management:
  health:
    mail:
      enabled: false
logging:
  level:
    root: ERROR
    org.springframework.web: DEBUG
    org.hibernate: ERROR
---
spring:
  profiles: production
  jpa:
    database: MYSQL
    generate-ddl: true
    hibernate:
      ddl-auto: update #create-drop
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/bookingservice?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
---
spring:
  profiles: production, default
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://fridge.eureka.annabales.dev:8761/eureka
  instance:
    preferIpAddress: true
laden:
  bank:
    url: http://aibank
---
spring:
  profiles: testing, default
  jpa:
    database: H2
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
  h2:
    console:
      enabled: true
  cloud:
    gcp:
      pubsub:
        enabled: false
---
spring:
  profiles: testing
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
laden:
  bank:
    url: http://localhost:8000
